### ISSUE TITLE
有时上传会无效，必须得再传一次。

### ISSUE THREAD

**Issue by kevzcr** [jinzhi0123/picgo-plugin-alist#14]
前段时间修改了alist的 "token_expires_in": 4800,  不知道会不会和这有关，上传失灵让人很蹦，每次都要撕开网页看一下。

**Comment by jinzhi0123** [comment]
请提供一下上传失灵前后一段时间内的日志文件呢

**Comment by kevzcr** [comment]
> 请提供一下上传失灵前后一段时间内的日志文件呢

2022-11-15 21:00:24 [PicGo ERROR] 
------Error Stack Begin------
Error: image not found in clipboard
    at dt.upload (C:\Users\D\AppData\Roaming\npm\node_modules\picgo\dist\index.cjs.js:1:44992)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\D\AppData\Roaming\npm\node_modules\picgo\dist\index.cjs.js:1:3206
-------Error Stack End------- 
2022-11-15 21:02:06 [PicGo INFO] Before transform 
2022-11-15 21:02:06 [PicGo INFO] Transforming... Current transformer is [path] 
2022-11-15 21:02:06 [PicGo INFO] Before upload 
2022-11-15 21:02:06 [PicGo INFO] Uploading... Current uploader is [alist] 
2022-11-15 21:02:06 [PicGo INFO] [信息]version:3,path:/6/Apps/pic1029,fileName:20221115210204.png,url:http://127.0.0.1:5244 
2022-11-15 21:02:06 [PicGo INFO] [信息]已经写入文件C:\Users\D\AppData\Local\Temp\20221115210204.png 
2022-11-15 21:02:07 [PicGo INFO] [请求结果]"{\"code\":200,\"message\":\"success\",\"data\":null}" 
2022-11-15 21:02:07 [PicGo SUCCESS] 
http://127.0.0.1:5244/d//6/Apps/pic1029/20221115210204.png 
2022-11-15 22:28:09 [PicGo ERROR] 
------Error Stack Begin------
Error: image not found in clipboard
    at dt.upload (C:\Users\D\AppData\Roaming\npm\node_modules\picgo\dist\index.cjs.js:1:44992)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\D\AppData\Roaming\npm\node_modules\picgo\dist\index.cjs.js:1:3206
-------Error Stack End-------

**Comment by kevzcr** [comment]
失败后再传一次就好了。

------Error Stack Begin------
Error: image not found in clipboard
    at dt.upload (C:\Users\D\AppData\Roaming\npm\node_modules\picgo\dist\index.cjs.js:1:44992)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\D\AppData\Roaming\npm\node_modules\picgo\dist\index.cjs.js:1:3206
-------Error Stack End------- 
2022-11-15 22:37:42 [PicGo INFO] Before transform 
2022-11-15 22:37:42 [PicGo INFO] Transforming... Current transformer is [path] 
2022-11-15 22:37:43 [PicGo INFO] Before upload 
2022-11-15 22:37:43 [PicGo INFO] Uploading... Current uploader is [alist] 
2022-11-15 22:37:43 [PicGo INFO] [信息]version:3,path:/6/Apps/pic1029,fileName:20221115223717.png,url:http://127.0.0.1:5244 
2022-11-15 22:37:43 [PicGo INFO] [信息]已经写入文件C:\Users\D\AppData\Local\Temp\20221115223717.png 
2022-11-15 22:37:48 [PicGo INFO] [请求结果]"{\"code\":200,\"message\":\"success\",\"data\":null}" 
2022-11-15 22:37:48 [PicGo SUCCESS] 
http://127.0.0.1:5244/d//6/Apps/pic1029/20221115223717.png

**Comment by jinzhi0123** [comment]
Error: image not found in clipboard
剪贴板部分不由插件控制，由picgo本体控制。
错误可能发生在picgo或其他调用picgo的软件（如typora），或由人为操作失误产生。
你可以检查一下直接使用picgo是否会产生这样的问题。

**Comment by kevzcr** [comment]
自己也一直在排查，好吧，至少现在排除了插件的问题。
