### ISSUE TITLE
[PicGo ERROR] [上传操作]

### ISSUE THREAD

**Issue by veistory** [jinzhi0123/picgo-plugin-alist#7]
[PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\bt.png' 
'D:\TEMP‘为设备自定义的缓存路径，实际图片存放位置不在此处。
上传图片就报错，只成功过一次上传的还不是图片，阿里云的就没问题。
PicGO版本2.3.1beta7

**Comment by jinzhi0123** [comment]
可以更新一下插件的最新版本噢；
如果还是出现问题的话，可以提供一下picgo日志（Picgo-PicGo设置-打开日志文件）。

**Comment by veistory** [comment]
更新插件后出现新情况，附上之前日志和新的日志

-------Error Stack End------- 
2022-10-25 09:32:38 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\P$N0G@%4@(KG{ZROD[XIDQE.jpg' 
2022-10-25 09:33:03 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\R-C.jpg' 
2022-10-25 09:33:57 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\R-C.jpg' 
2022-10-25 09:34:20 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\R-C.jpg' 
2022-10-25 09:35:05 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\R-C.jpg' 
2022-10-25 09:40:05 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\0137325784517f0000012e7ef049b6.png' 
2022-10-25 09:40:54 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\R-C.jpg' 
2022-10-25 09:41:55 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\R-C.jpg' 
2022-10-25 09:48:46 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\0137325784517f0000012e7ef049b6.png' 
2022-10-25 09:50:58 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\0137325784517f0000012e7ef049b6.png' 
2022-10-25 09:52:51 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\bt.png' 
2022-10-25 09:53:26 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\bt.png' 
2022-10-25 09:53:57 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\bt.png' 
2022-10-25 10:04:26 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\bt.png' 
2022-10-25 10:04:46 [PicGo WARN] can't get D:\ADD\Documents\经纬度距离计算.xlsx's image size 
2022-10-25 10:04:46 [PicGo WARN] fallback to 200 * 200 
2022-10-25 10:06:21 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\练习10.jpeg' 
2022-10-25 10:07:03 [PicGo WARN] can't get C:\Users\ADD\Desktop\10.13-10.19.xlsx's image size 
2022-10-25 10:07:03 [PicGo WARN] fallback to 200 * 200 
2022-10-25 10:07:03 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\10.13-10.19.xlsx' 
2022-10-25 10:07:23 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\bt.png' 
2022-10-25 10:07:30 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\光伏现场视图.jpg' 
2022-10-25 10:07:41 [PicGo WARN] can't get D:\ADD\Documents\经纬度距离计算.xlsx's image size 
2022-10-25 10:07:41 [PicGo WARN] fallback to 200 * 200 
2022-10-25 10:07:41 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\经纬度距离计算.xlsx' 
2022-10-25 10:08:31 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\bt.png' 
2022-10-25 10:09:52 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\icon.png' 
2022-10-25 10:12:19 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\bt.png' 
2022-10-25 10:13:00 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\bt.png' 
2022-10-25 10:13:17 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\ipa.png' 
2022-10-25 10:13:40 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\ipa.png' 
2022-10-25 10:14:03 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\ipa.png' 
2022-10-25 10:15:34 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\ipa.png' 
2022-10-25 10:25:18 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\bt.png' 
2022-10-25 10:27:09 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\bt.png' 
2022-10-25 10:28:03 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\IMG_0090.JPG' 
2022-10-25 10:39:24 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\IMG_0090.JPG' 
2022-10-25 10:40:57 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\IMG_0090.JPG' 
2022-10-28 09:39:15 [PicGo ERROR] [上传操作]异常：ENOENT: no such file or directory, open 'D:\TEMP\20221028093914.png' 
2022-10-28 14:17:00 [PicGo ERROR] 
------Error Stack Begin------
Error: [上传操作]异常：[请求出错]"<!DOCTYPE html>\n<html lang=\"en\" translate=\"no\">\n  <head>\n    <script src=\"https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll\"></script>\n    <meta charset=\"utf-8\" >\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" >\n    <meta name=\"referrer\" content=\"same-origin\" >\n    <meta name=\"generator\" content=\"AList V3\" >\n    <meta name=\"theme-color\" content=\"#000000\" >\n    <meta name=\"google\" content=\"notranslate\" >\n    <script       src=\"https://g.alicdn.com/IMM/office-js/1.1.5/aliyun-web-office-sdk.min.js\"\n      async\n    ></script>\n    <link       rel=\"shortcut icon\"\n      type=\"image/ico\"\n      href=\"https://app.solicat.cn/uploads/20221014/b91ec1220827be4fcb1a5d2d9de5a4e6.png\"\n    >\n    <title>Home</title>\n    <script>\n      window.ALIST = {\n        cdn: '',\n        monaco_cdn: undefined,\n        base_path: '',\n        api: 'https://pan.solicat.cn',\n        main_color: '#658ebe',\n      }\n      window.__dynamic_base__ = window.ALIST.cdn || \"\"\n    </script>\n    \n    \n    <script type=\"module\">try{import.meta.url;import(\"_\").catch(()=>1);}catch(e){}window.__vite_is_modern_browser=true;</script>\n    <script type=\"module\">!function(){if(window.__vite_is_modern_browser)return;console.warn(\"vite: loading legacy build because dynamic import or import.meta.url is unsupported, syntax error above should be ignored\");var e=document.getElementById(\"vite-legacy-polyfill\"),n=document.createElement(\"script\");n.src= window.__dynamic_base__+e.getAttribute('data-src'),n.onload=function(){System.import( window.__dynamic_base__+document.getElementById('vite-legacy-entry').getAttribute('data-src'))},document.body.appendChild(n)}();</script>\n    <script>\n(function(){\nvar preloads = [{\"parentTagName\":\"head\",\"tagName\":\"script\",\"attrs\":{\"type\":\"module\",\"crossorigin\":\"\",\"src\":\"/assets/index.786270b3.js\"}},{\"parentTagName\":\"head\",\"tagName\":\"link\",\"attrs\":{\"rel\":\"stylesheet\",\"href\":\"/assets/index.659f4289.css\"}}];\nfunction setAttribute(target, attrs) {\nfor (var key in attrs) {\n  target.setAttribute(key, attrs[key]);\n}\nreturn target;\n};\nfor(var i = 0; i < preloads.length; i++){\nvar item = preloads[i]\nvar childNode = document.createElement(item.tagName);\nsetAttribute(childNode, item.attrs)\nif( window.__dynamic_base__) {\n  if(item.tagName == 'link') {\n    setAttribute(childNode, { href:  window.__dynamic_base__ + item.attrs.href })\n  } else if (item.tagName == 'script') {\n    setAttribute(childNode, { src:  window.__dynamic_base__ + item.attrs.src })\n  }\n}\ndocument.getElementsByTagName(item.parentTagName)[0].appendChild(childNode);\n}\n})();\n</script>\n</head>\n  <body>\n    <noscript>You need to enable JavaScript to run this app.</noscript>\n    <div id=\"root\"></div>\n\n    \n    \n    <script nomodule>!function(){var e=document,t=e.createElement(\"script\");if(!(\"noModule\"in t)&&\"onbeforeload\"in t){var n=!1;e.addEventListener(\"beforeload\",(function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute(\"nomodule\")||!n)return;e.preventDefault()}),!0),t.type=\"module\",t.src=\".\",e.head.appendChild(t),t.remove()}}();</script>\n    <script nomodule crossorigin id=\"vite-legacy-polyfill\" data-src=\"/assets/polyfills-legacy.eec2d8ef.js\">!(function() {\n      var e = document.createElement('script')\n      e.src =  window.__dynamic_base__ + document.getElementById('vite-legacy-polyfill').getAttribute('data-src');\n      e.onload = function() {\n        System.import( window.__dynamic_base__+document.getElementById('vite-legacy-entry').getAttribute('data-src'))\n      };\n      document.body.appendChild(e)\n    })();</script>\n    <script nomodule crossorigin id=\"vite-legacy-entry\" data-src=\"/assets/index-legacy.2451467d.js\"></script>\n  </body>\n</html>\n"
    at Object.handle (C:\Users\ADD\AppData\Roaming\picgo\node_modules\picgo-plugin-alist\dist\index.js:93:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17188)
    at async $e.start (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15959)
    at async Tt.upload (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:70812)
    at async Object.upload (D:\Program Files\PicGo\resources\app.asar\background.js:2:649543)
    at async In (D:\Program Files\PicGo\resources\app.asar\background.js:2:652443)
-------Error Stack End------- 
2022-10-28 14:19:05 [PicGo ERROR] 
------Error Stack Begin------
Error: [上传操作]异常：[请求出错]"<!DOCTYPE html>\n<html lang=\"en\" translate=\"no\">\n  <head>\n    <script src=\"https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll\"></script>\n    <meta charset=\"utf-8\" >\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" >\n    <meta name=\"referrer\" content=\"same-origin\" >\n    <meta name=\"generator\" content=\"AList V3\" >\n    <meta name=\"theme-color\" content=\"#000000\" >\n    <meta name=\"google\" content=\"notranslate\" >\n    <script       src=\"https://g.alicdn.com/IMM/office-js/1.1.5/aliyun-web-office-sdk.min.js\"\n      async\n    ></script>\n    <link       rel=\"shortcut icon\"\n      type=\"image/ico\"\n      href=\"https://app.solicat.cn/uploads/20221014/b91ec1220827be4fcb1a5d2d9de5a4e6.png\"\n    >\n    <title>Home</title>\n    <script>\n      window.ALIST = {\n        cdn: '',\n        monaco_cdn: undefined,\n        base_path: '',\n        api: 'https://pan.solicat.cn',\n        main_color: '#658ebe',\n      }\n      window.__dynamic_base__ = window.ALIST.cdn || \"\"\n    </script>\n    \n    \n    <script type=\"module\">try{import.meta.url;import(\"_\").catch(()=>1);}catch(e){}window.__vite_is_modern_browser=true;</script>\n    <script type=\"module\">!function(){if(window.__vite_is_modern_browser)return;console.warn(\"vite: loading legacy build because dynamic import or import.meta.url is unsupported, syntax error above should be ignored\");var e=document.getElementById(\"vite-legacy-polyfill\"),n=document.createElement(\"script\");n.src= window.__dynamic_base__+e.getAttribute('data-src'),n.onload=function(){System.import( window.__dynamic_base__+document.getElementById('vite-legacy-entry').getAttribute('data-src'))},document.body.appendChild(n)}();</script>\n    <script>\n(function(){\nvar preloads = [{\"parentTagName\":\"head\",\"tagName\":\"script\",\"attrs\":{\"type\":\"module\",\"crossorigin\":\"\",\"src\":\"/assets/index.786270b3.js\"}},{\"parentTagName\":\"head\",\"tagName\":\"link\",\"attrs\":{\"rel\":\"stylesheet\",\"href\":\"/assets/index.659f4289.css\"}}];\nfunction setAttribute(target, attrs) {\nfor (var key in attrs) {\n  target.setAttribute(key, attrs[key]);\n}\nreturn target;\n};\nfor(var i = 0; i < preloads.length; i++){\nvar item = preloads[i]\nvar childNode = document.createElement(item.tagName);\nsetAttribute(childNode, item.attrs)\nif( window.__dynamic_base__) {\n  if(item.tagName == 'link') {\n    setAttribute(childNode, { href:  window.__dynamic_base__ + item.attrs.href })\n  } else if (item.tagName == 'script') {\n    setAttribute(childNode, { src:  window.__dynamic_base__ + item.attrs.src })\n  }\n}\ndocument.getElementsByTagName(item.parentTagName)[0].appendChild(childNode);\n}\n})();\n</script>\n</head>\n  <body>\n    <noscript>You need to enable JavaScript to run this app.</noscript>\n    <div id=\"root\"></div>\n\n    \n    \n    <script nomodule>!function(){var e=document,t=e.createElement(\"script\");if(!(\"noModule\"in t)&&\"onbeforeload\"in t){var n=!1;e.addEventListener(\"beforeload\",(function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute(\"nomodule\")||!n)return;e.preventDefault()}),!0),t.type=\"module\",t.src=\".\",e.head.appendChild(t),t.remove()}}();</script>\n    <script nomodule crossorigin id=\"vite-legacy-polyfill\" data-src=\"/assets/polyfills-legacy.eec2d8ef.js\">!(function() {\n      var e = document.createElement('script')\n      e.src =  window.__dynamic_base__ + document.getElementById('vite-legacy-polyfill').getAttribute('data-src');\n      e.onload = function() {\n        System.import( window.__dynamic_base__+document.getElementById('vite-legacy-entry').getAttribute('data-src'))\n      };\n      document.body.appendChild(e)\n    })();</script>\n    <script nomodule crossorigin id=\"vite-legacy-entry\" data-src=\"/assets/index-legacy.2451467d.js\"></script>\n  </body>\n</html>\n"
    at Object.handle (C:\Users\ADD\AppData\Roaming\picgo\node_modules\picgo-plugin-alist\dist\index.js:93:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17188)
    at async $e.start (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15959)
    at async Tt.upload (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:70812)
    at async Object.upload (D:\Program Files\PicGo\resources\app.asar\background.js:2:649543)
    at async In (D:\Program Files\PicGo\resources\app.asar\background.js:2:652443)
-------Error Stack End------- 
2022-10-28 14:22:22 [PicGo ERROR] 
------Error Stack Begin------
Error: [上传操作]异常：[请求出错]"<!DOCTYPE html>\n<html lang=\"en\" translate=\"no\">\n  <head>\n    <script src=\"https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll\"></script>\n    <meta charset=\"utf-8\" >\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" >\n    <meta name=\"referrer\" content=\"same-origin\" >\n    <meta name=\"generator\" content=\"AList V3\" >\n    <meta name=\"theme-color\" content=\"#000000\" >\n    <meta name=\"google\" content=\"notranslate\" >\n    <script       src=\"https://g.alicdn.com/IMM/office-js/1.1.5/aliyun-web-office-sdk.min.js\"\n      async\n    ></script>\n    <link       rel=\"shortcut icon\"\n      type=\"image/ico\"\n      href=\"https://app.solicat.cn/uploads/20221014/b91ec1220827be4fcb1a5d2d9de5a4e6.png\"\n    >\n    <title>Home</title>\n    <script>\n      window.ALIST = {\n        cdn: '',\n        monaco_cdn: undefined,\n        base_path: '',\n        api: 'https://pan.solicat.cn',\n        main_color: '#658ebe',\n      }\n      window.__dynamic_base__ = window.ALIST.cdn || \"\"\n    </script>\n    \n    \n    <script type=\"module\">try{import.meta.url;import(\"_\").catch(()=>1);}catch(e){}window.__vite_is_modern_browser=true;</script>\n    <script type=\"module\">!function(){if(window.__vite_is_modern_browser)return;console.warn(\"vite: loading legacy build because dynamic import or import.meta.url is unsupported, syntax error above should be ignored\");var e=document.getElementById(\"vite-legacy-polyfill\"),n=document.createElement(\"script\");n.src= window.__dynamic_base__+e.getAttribute('data-src'),n.onload=function(){System.import( window.__dynamic_base__+document.getElementById('vite-legacy-entry').getAttribute('data-src'))},document.body.appendChild(n)}();</script>\n    <script>\n(function(){\nvar preloads = [{\"parentTagName\":\"head\",\"tagName\":\"script\",\"attrs\":{\"type\":\"module\",\"crossorigin\":\"\",\"src\":\"/assets/index.786270b3.js\"}},{\"parentTagName\":\"head\",\"tagName\":\"link\",\"attrs\":{\"rel\":\"stylesheet\",\"href\":\"/assets/index.659f4289.css\"}}];\nfunction setAttribute(target, attrs) {\nfor (var key in attrs) {\n  target.setAttribute(key, attrs[key]);\n}\nreturn target;\n};\nfor(var i = 0; i < preloads.length; i++){\nvar item = preloads[i]\nvar childNode = document.createElement(item.tagName);\nsetAttribute(childNode, item.attrs)\nif( window.__dynamic_base__) {\n  if(item.tagName == 'link') {\n    setAttribute(childNode, { href:  window.__dynamic_base__ + item.attrs.href })\n  } else if (item.tagName == 'script') {\n    setAttribute(childNode, { src:  window.__dynamic_base__ + item.attrs.src })\n  }\n}\ndocument.getElementsByTagName(item.parentTagName)[0].appendChild(childNode);\n}\n})();\n</script>\n</head>\n  <body>\n    <noscript>You need to enable JavaScript to run this app.</noscript>\n    <div id=\"root\"></div>\n\n    \n    \n    <script nomodule>!function(){var e=document,t=e.createElement(\"script\");if(!(\"noModule\"in t)&&\"onbeforeload\"in t){var n=!1;e.addEventListener(\"beforeload\",(function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute(\"nomodule\")||!n)return;e.preventDefault()}),!0),t.type=\"module\",t.src=\".\",e.head.appendChild(t),t.remove()}}();</script>\n    <script nomodule crossorigin id=\"vite-legacy-polyfill\" data-src=\"/assets/polyfills-legacy.eec2d8ef.js\">!(function() {\n      var e = document.createElement('script')\n      e.src =  window.__dynamic_base__ + document.getElementById('vite-legacy-polyfill').getAttribute('data-src');\n      e.onload = function() {\n        System.import( window.__dynamic_base__+document.getElementById('vite-legacy-entry').getAttribute('data-src'))\n      };\n      document.body.appendChild(e)\n    })();</script>\n    <script nomodule crossorigin id=\"vite-legacy-entry\" data-src=\"/assets/index-legacy.2451467d.js\"></script>\n  </body>\n</html>\n"
    at Object.handle (C:\Users\ADD\AppData\Roaming\picgo\node_modules\picgo-plugin-alist\dist\index.js:93:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17188)
    at async $e.start (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15959)
    at async Tt.upload (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:70812)
    at async Object.upload (D:\Program Files\PicGo\resources\app.asar\background.js:2:649543)
    at async In (D:\Program Files\PicGo\resources\app.asar\background.js:2:652443)
-------Error Stack End------- 
2022-10-28 14:23:30 [PicGo ERROR] 
------Error Stack Begin------
Error: [上传操作]异常：[请求出错]"<!DOCTYPE html>\n<html lang=\"en\" translate=\"no\">\n  <head>\n    <script src=\"https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll\"></script>\n    <meta charset=\"utf-8\" >\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" >\n    <meta name=\"referrer\" content=\"same-origin\" >\n    <meta name=\"generator\" content=\"AList V3\" >\n    <meta name=\"theme-color\" content=\"#000000\" >\n    <meta name=\"google\" content=\"notranslate\" >\n    <script       src=\"https://g.alicdn.com/IMM/office-js/1.1.5/aliyun-web-office-sdk.min.js\"\n      async\n    ></script>\n    <link       rel=\"shortcut icon\"\n      type=\"image/ico\"\n      href=\"https://app.solicat.cn/uploads/20221014/b91ec1220827be4fcb1a5d2d9de5a4e6.png\"\n    >\n    <title>Home</title>\n    <script>\n      window.ALIST = {\n        cdn: '',\n        monaco_cdn: undefined,\n        base_path: '',\n        api: 'https://pan.solicat.cn',\n        main_color: '#658ebe',\n      }\n      window.__dynamic_base__ = window.ALIST.cdn || \"\"\n    </script>\n    \n    \n    <script type=\"module\">try{import.meta.url;import(\"_\").catch(()=>1);}catch(e){}window.__vite_is_modern_browser=true;</script>\n    <script type=\"module\">!function(){if(window.__vite_is_modern_browser)return;console.warn(\"vite: loading legacy build because dynamic import or import.meta.url is unsupported, syntax error above should be ignored\");var e=document.getElementById(\"vite-legacy-polyfill\"),n=document.createElement(\"script\");n.src= window.__dynamic_base__+e.getAttribute('data-src'),n.onload=function(){System.import( window.__dynamic_base__+document.getElementById('vite-legacy-entry').getAttribute('data-src'))},document.body.appendChild(n)}();</script>\n    <script>\n(function(){\nvar preloads = [{\"parentTagName\":\"head\",\"tagName\":\"script\",\"attrs\":{\"type\":\"module\",\"crossorigin\":\"\",\"src\":\"/assets/index.786270b3.js\"}},{\"parentTagName\":\"head\",\"tagName\":\"link\",\"attrs\":{\"rel\":\"stylesheet\",\"href\":\"/assets/index.659f4289.css\"}}];\nfunction setAttribute(target, attrs) {\nfor (var key in attrs) {\n  target.setAttribute(key, attrs[key]);\n}\nreturn target;\n};\nfor(var i = 0; i < preloads.length; i++){\nvar item = preloads[i]\nvar childNode = document.createElement(item.tagName);\nsetAttribute(childNode, item.attrs)\nif( window.__dynamic_base__) {\n  if(item.tagName == 'link') {\n    setAttribute(childNode, { href:  window.__dynamic_base__ + item.attrs.href })\n  } else if (item.tagName == 'script') {\n    setAttribute(childNode, { src:  window.__dynamic_base__ + item.attrs.src })\n  }\n}\ndocument.getElementsByTagName(item.parentTagName)[0].appendChild(childNode);\n}\n})();\n</script>\n</head>\n  <body>\n    <noscript>You need to enable JavaScript to run this app.</noscript>\n    <div id=\"root\"></div>\n\n    \n    \n    <script nomodule>!function(){var e=document,t=e.createElement(\"script\");if(!(\"noModule\"in t)&&\"onbeforeload\"in t){var n=!1;e.addEventListener(\"beforeload\",(function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute(\"nomodule\")||!n)return;e.preventDefault()}),!0),t.type=\"module\",t.src=\".\",e.head.appendChild(t),t.remove()}}();</script>\n    <script nomodule crossorigin id=\"vite-legacy-polyfill\" data-src=\"/assets/polyfills-legacy.eec2d8ef.js\">!(function() {\n      var e = document.createElement('script')\n      e.src =  window.__dynamic_base__ + document.getElementById('vite-legacy-polyfill').getAttribute('data-src');\n      e.onload = function() {\n        System.import( window.__dynamic_base__+document.getElementById('vite-legacy-entry').getAttribute('data-src'))\n      };\n      document.body.appendChild(e)\n    })();</script>\n    <script nomodule crossorigin id=\"vite-legacy-entry\" data-src=\"/assets/index-legacy.2451467d.js\"></script>\n  </body>\n</html>\n"
    at Object.handle (C:\Users\ADD\AppData\Roaming\picgo\node_modules\picgo-plugin-alist\dist\index.js:93:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17188)
    at async $e.start (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15959)
    at async Tt.upload (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:70812)
    at async Object.upload (D:\Program Files\PicGo\resources\app.asar\background.js:2:649543)
    at async In (D:\Program Files\PicGo\resources\app.asar\background.js:2:652443)
-------Error Stack End------- 
2022-10-28 14:27:14 [PicGo ERROR] 
------Error Stack Begin------
Error: [上传操作]异常：[请求出错]"<!DOCTYPE html>\n<html lang=\"en\" translate=\"no\">\n  <head>\n    <script src=\"https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll\"></script>\n    <meta charset=\"utf-8\" >\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" >\n    <meta name=\"referrer\" content=\"same-origin\" >\n    <meta name=\"generator\" content=\"AList V3\" >\n    <meta name=\"theme-color\" content=\"#000000\" >\n    <meta name=\"google\" content=\"notranslate\" >\n    <script       src=\"https://g.alicdn.com/IMM/office-js/1.1.5/aliyun-web-office-sdk.min.js\"\n      async\n    ></script>\n    <link       rel=\"shortcut icon\"\n      type=\"image/ico\"\n      href=\"https://app.solicat.cn/uploads/20221014/b91ec1220827be4fcb1a5d2d9de5a4e6.png\"\n    >\n    <title>Home</title>\n    <script>\n      window.ALIST = {\n        cdn: '',\n        monaco_cdn: undefined,\n        base_path: '',\n        api: 'https://pan.solicat.cn',\n        main_color: '#658ebe',\n      }\n      window.__dynamic_base__ = window.ALIST.cdn || \"\"\n    </script>\n    \n    \n    <script type=\"module\">try{import.meta.url;import(\"_\").catch(()=>1);}catch(e){}window.__vite_is_modern_browser=true;</script>\n    <script type=\"module\">!function(){if(window.__vite_is_modern_browser)return;console.warn(\"vite: loading legacy build because dynamic import or import.meta.url is unsupported, syntax error above should be ignored\");var e=document.getElementById(\"vite-legacy-polyfill\"),n=document.createElement(\"script\");n.src= window.__dynamic_base__+e.getAttribute('data-src'),n.onload=function(){System.import( window.__dynamic_base__+document.getElementById('vite-legacy-entry').getAttribute('data-src'))},document.body.appendChild(n)}();</script>\n    <script>\n(function(){\nvar preloads = [{\"parentTagName\":\"head\",\"tagName\":\"script\",\"attrs\":{\"type\":\"module\",\"crossorigin\":\"\",\"src\":\"/assets/index.786270b3.js\"}},{\"parentTagName\":\"head\",\"tagName\":\"link\",\"attrs\":{\"rel\":\"stylesheet\",\"href\":\"/assets/index.659f4289.css\"}}];\nfunction setAttribute(target, attrs) {\nfor (var key in attrs) {\n  target.setAttribute(key, attrs[key]);\n}\nreturn target;\n};\nfor(var i = 0; i < preloads.length; i++){\nvar item = preloads[i]\nvar childNode = document.createElement(item.tagName);\nsetAttribute(childNode, item.attrs)\nif( window.__dynamic_base__) {\n  if(item.tagName == 'link') {\n    setAttribute(childNode, { href:  window.__dynamic_base__ + item.attrs.href })\n  } else if (item.tagName == 'script') {\n    setAttribute(childNode, { src:  window.__dynamic_base__ + item.attrs.src })\n  }\n}\ndocument.getElementsByTagName(item.parentTagName)[0].appendChild(childNode);\n}\n})();\n</script>\n</head>\n  <body>\n    <noscript>You need to enable JavaScript to run this app.</noscript>\n    <div id=\"root\"></div>\n\n    \n    \n    <script nomodule>!function(){var e=document,t=e.createElement(\"script\");if(!(\"noModule\"in t)&&\"onbeforeload\"in t){var n=!1;e.addEventListener(\"beforeload\",(function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute(\"nomodule\")||!n)return;e.preventDefault()}),!0),t.type=\"module\",t.src=\".\",e.head.appendChild(t),t.remove()}}();</script>\n    <script nomodule crossorigin id=\"vite-legacy-polyfill\" data-src=\"/assets/polyfills-legacy.eec2d8ef.js\">!(function() {\n      var e = document.createElement('script')\n      e.src =  window.__dynamic_base__ + document.getElementById('vite-legacy-polyfill').getAttribute('data-src');\n      e.onload = function() {\n        System.import( window.__dynamic_base__+document.getElementById('vite-legacy-entry').getAttribute('data-src'))\n      };\n      document.body.appendChild(e)\n    })();</script>\n    <script nomodule crossorigin id=\"vite-legacy-entry\" data-src=\"/assets/index-legacy.2451467d.js\"></script>\n  </body>\n</html>\n"
    at Object.handle (C:\Users\ADD\AppData\Roaming\picgo\node_modules\picgo-plugin-alist\dist\index.js:93:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17188)
    at async $e.start (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15959)
    at async Tt.upload (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:70812)
    at async Object.upload (D:\Program Files\PicGo\resources\app.asar\background.js:2:649543)
    at async In (D:\Program Files\PicGo\resources\app.asar\background.js:2:652443)
-------Error Stack End-------

**Comment by jinzhi0123** [comment]
该报错通常是插件配置项（alist地址或版本）填写错误造成的，可以提供一下你的配置
另外可以再更新一下插件噢（修复了一个小问题）
如果还是报错，可以再次提供一下picgo日志

**Comment by jinzhi0123** [comment]
更新下插件噢，新版本优化了配置项的参数传入。

**Comment by veistory** [comment]
> 更新下插件噢，新版本优化了配置项的参数传入。

插件更新到1.2.0后已可以正常上传，感谢！
